trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'


steps: 
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build

- script: npm test --ci --reporters=default --reporters=jest-junit
  env:
    CI: true

- task: PublishTestResults@2
  displayName: "Publish Test Results"
  inputs:
    testResultsFiles: junit.xml
    mergeTestResults: true
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
