trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'


steps: 
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: :'npm run build'
  
- script: npm test -- --coverage --ci --reporters=default --reporters=jest-junit --coverageReporters=cobertura
  env:
    CI: true
  displayName: 'Run tests'
  

- task: PublishTestResults@2
  displayName: "Publish Test Results"
  inputs:
    testResultsFiles: junit.xml
    mergeTestResults: true
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: "Publish code coverage"
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/coverage"
    failIfCoverageEmpty: true